server:
  port: 9004
spring:
  application:
    name: child-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.50.16:8848
    gateway:
      routes:
        - id: child-consumer
          uri: lb://child-consumer
          predicates:
            - Path=/consumer/*
